name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Find all *.java files and then compile them
      run: cd src && find -name "*.java" > java_files.txt && javac @java_files.txt && ls
